import time
import servo
from periphery import PWM
from synDef import *
class hard_code():

  def __init__():
     self.servos = servo.Servo()
  def top_left():
      self.servos.moveBothServos(0, 180)
      time.sleep(1)

  def top_right():
      self.servos.moveBothServos(180, 180)
      time.sleep(1)
      
  def bottom_left():
      self.servos.moveBothServos(0, 0)
      time.sleep(1)
      
  def bottom_right():
      self.servos.moveBothServos(180, 0)
      time.sleep(1)
      
  def delay():
    time.sleep(1)
    

  def easy_maze():
    self.servos.moveBothServos(0, 180)
    delay()
    self.servos.moveBothServos(0, 0)
    delay()
    #self.servos.moveBothServos(180, 0)
    #delay()
    self.servos.moveBothServos(180, 180)
    delay()
    self.servos.moveBothServos(180,0)
    delay()
    self.servos.moveBothServos(0,0)
    delay()
    self.servos.moveBothServos(0,180)
    delay()
    self.servos.moveBothServos(0, 0)
    delay()
    self.servos.moveBothServos(120, 0)
    time.sleep(1.25)
    self.servos.moveBothServos(0, 0)
    delay()

    self.servos.moveBothServos(180,180)
    delay()
    self.servos.moveBothServos(180, 0)
    delay()
    self.servos.moveBothServos(180, 180)
    delay()
    self.servos.moveBothServos(0, 0)
    delay()
    self.servos.moveBothServos(0, 180)
    delay()
    self.servos.moveBothServos(0, 180)
    delay()
    self.servos.moveBothServos(180, 180)
    delay()
    self.self.servos.moveBothServos(180, 0)
    delay()
    self.servos.moveBothServos(0, 30)
    delay()
    self.servos.moveBothServos(180, 0)
    delay()
    self.servos.moveBothServos(0, 0)
    delay()
    self.servos.moveBothServos(180, 0)
    delay()
    self.servos.moveBothServos(0, 0)
    delay()
    self.servos.moveBothServos(0, 180)
    delay()
    self.servos.moveBothServos(0, 0)
    delay()
    
  def medium_maze():
    self.servos.moveBothServos(0, 180)
    delay()
    self.servos.moveBothServos(60, 0)
    delay()
    self.servos.moveBothServos(180, 0)
    delay()
    self.servos.moveBothServos(0, 120)
    delay()
    self.servos.moveBothServos(0, 0)
    delay()
    self.servos.moveBothServos(180, 0)
    delay()
    self.servos.moveBothServos(180, 180)
    delay()
    self.servos.moveBothServos(180, 0)
    delay()
    #from hole 9
    self.servos.moveBothServos(0, 180)
    delay()
    self.servos.moveBothServos(0, 0)
    delay()
    self.servos.moveBothServos(90,90)
    delay()
    self.servos.moveBothServos(120, 90)
    delay()
    self.servos.moveBothServos(90, 90)
    delay()
    #straight up pass hole 12
    self.servos.moveBothServos(90, 180)
    delay()
    self.servos.moveBothServos(110, 180)
    delay()
    self.servos.moveBothServos(90, 0)
    delay()
    #stay before hole 16
    self.servos.moveBothServos(180, 0)
    delay()
    self.servos.moveBothServos(180, 180)
    delay()
    self.servos.moveBothServos(180, 0)
    delay() 
    self.servos.moveBothServos(0, 0)
    delay()
    self.servos.moveBothServos(120, 0)
    delay()
    self.servos.moveBothServos(0, 0)
    delay()
    
  def medium_maze_new():
      
      top_left()
      bottom_left()
      bottom_right()
      top_left()
      self.servos.moveBothServos(0,0)
      time.sleep(0.5)
      bottom_right()
      top_right()
      bottom_right()
      self.servos.moveBothServos(180,120)
      delay()
      bottom_left()
      self.servos.moveBothServos(180,0)
      time.sleep(0.5)
      bottom_left()
    
  servos = servo.servo()

  def var_delay(seconds):
      time.sleep(seconds)
  def hard_maze():
      self.servos.moveBothServos(0, 90)
      var_delay(0.6)
      self.servos.moveBothServos(40, 30)
      var_delay(0.5)
      #past hole 1 and 2
      self.servos.moveBothServos(60, 130)
      var_delay(0.3)
      self.servos.moveBothServos(80, 0)
      #check point 1
      delay()
      self.servos.moveBothServos(110, 90)
      var_delay(0.7)
      self.servos.moveBothServos(110, 60)
      var_delay(0.5)
      self.servos.moveBothServos(60, 100)
      var_delay(0.5)
      self.servos.moveBothServos(120,100)
      var_delay(0.5)
      self.servos.moveBothServos(70, 60)
      #past hole 6
      var_delay(0.6)
      self.servos.moveBothServos(105, 60)
      var_delay(0.3)
      self.servos.moveBothServos(70, 70)
      #bottom left corner
      var_delay(0.5)
      self.servos.moveBothServos(110, 90)
      delay()
      self.servos.moveBothServos(120, 105)
      var_delay(0.4)
      self.servos.moveBothServos(30, 105)
      var_delay(0.4)
      self.servos.moveBothServos(110, 98)
      var_delay(0.5)
      self.servos.moveBothServos(90, 110)
      #past hole 17
      var_delay(0.8)
      self.servos.moveBothServos(70, 90)
      var_delay(0.3)
      self.servos.moveBothServos(70, 110)
      var_delay(0.5)
      self.servos.moveBothServos(90, 120)
      var_delay(0.6)
      self.servos.moveBothServos(140, 90)
      #past hole 23
      var_delay(0.7)
      self.servos.moveBothServos(90, 110)
      var_delay(0.5)
      self.servos.moveBothServos(110, 90)
      var_delay(0.3)
      self.servos.moveBothServos(90, 70)
      var_delay(0.5)
      self.servos.moveBothServos(110, 70)
      var_delay(0.4)
      self.servos.moveBothServos(70, 80)
      #past 27
      var_delay(0.3)
      self.servos.moveBothServos(90, 60)
      var_delay(0.35)
      self.servos.moveBothServos(70, 90)
      var_delay(0.5)
      self.servos.moveBothServos(90, 60)
      var_delay(0.7)
      #straight by 27
      self.servos.moveBothServos(100, 70)
      var_delay(0.2)
      self.servos.moveBothServos(50, 90)
      var_delay(0.25)
      self.servos.moveBothServos(90, 70)
      var_delay(0.2)
      self.servos.moveBothServos(70, 70)
      var_delay(0.4)
      #bottom middle of maze
      self.servos.moveBothServos(110, 90)
      var_delay(0.5)
      self.servos.moveBothServos(90, 110)
      var_delay(0.35)
      self.servos.moveBothServos(110, 110)
      var_delay(0.2)
      self.servos.moveBothServos(110, 90)
      var_delay(0.25)
      self.servos.moveBothServos(90, 60)
      var_delay(0.6)
      self.servos.moveBothServos(100, 90)
      var_delay(0.3)
      self.servos.moveBothServos(90, 110)
      var_delay(0.4)
      #below 41
      self.servos.moveBothServos(140, 90)
      var_delay(0.3)
      self.servos.moveBothServos(110, 110)
      var_delay(0.3)
      #past 43
      self.servos.moveBothServos(90, 120)
      var_delay(0.25)
      self.servos.moveBothServos(60, 90)
      var_delay(0.4)
      self.servos.moveBothServos(90, 110)
      var_delay(0.8)
      self.servos.moveBothServos(20,90)
      var_delay(0.25)
      self.servos.moveBothServos(90, 50)
      #below 46
      var_delay(0.3)
      self.servos.moveBothServos(60, 90)
      var_delay(0.5)
      self.servos.moveBothServos(110, 100)
      var_delay(0.7)
      self.servos.moveBothServos(90, 130)
      #below 50
      self.servos.moveBothServos(110, 110)
      var_delay(0.6)
      self.servos.moveBothServos(100, 90)
      var_delay(0.2)
      self.servos.moveBothServos(90, 140)
      var_delay(0.3)
      self.servos.moveBothServos(90, 30)
      var_delay(0.4)
      #above 51
      self.servos.moveBothServos(70, 90)
      var_delay(0.5)
      self.servos.moveBothServos(90, 110)
      var_delay(0.7)
      self.servos.moveBothServos(120, 90)
      var_delay(0.8)
      #below 55
      self.servos.moveBothServos(90, 60)
      var_delay(0.8)
      self.servos.moveBothServos(110, 60)
